// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9xP6j4L0xhV_1V3fdQwh9bAiqh2ditM',
    appId: '1:788818320442:web:ce2fd265419fb65202e903',
    messagingSenderId: '788818320442',
    projectId: 'tharwat-e-commerce',
    authDomain: 'tharwat-e-commerce.firebaseapp.com',
    storageBucket: 'tharwat-e-commerce.appspot.com',
    measurementId: 'G-SN9PEVJJF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGUd_kvWcBymqVqFEJ40LbzEU1QX9Ya8',
    appId: '1:788818320442:android:fd87fad8e256a30a02e903',
    messagingSenderId: '788818320442',
    projectId: 'tharwat-e-commerce',
    storageBucket: 'tharwat-e-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxw4HOyuJoxgbW6a5OA4qMTm_mgqEcek',
    appId: '1:788818320442:ios:808c90b1a478b59002e903',
    messagingSenderId: '788818320442',
    projectId: 'tharwat-e-commerce',
    storageBucket: 'tharwat-e-commerce.appspot.com',
    iosClientId: '788818320442-vng2951eum75vbcrgublrjld7rk1tukm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxw4HOyuJoxgbW6a5OA4qMTm_mgqEcek',
    appId: '1:788818320442:ios:fe3d8584a79e0fad02e903',
    messagingSenderId: '788818320442',
    projectId: 'tharwat-e-commerce',
    storageBucket: 'tharwat-e-commerce.appspot.com',
    iosClientId: '788818320442-ds15c7qif38a1peh0kchb4q71vdd463m.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
